apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-udacity
  labels:
    app: capstone-udacity
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-udacity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-udacity
    spec:
      containers:
      - image: minabedier/capstone-udacity:latest
        imagePullPolicy: Always
        name: capstone-udacity
        ports:
        - containerPort: 80
          protocol: TCP